#!/bin/bash

export BD_ASS=/homeworks/users/pixo/packages/int/badass
export BD_DB_SERVER=admin:admin@127.0.0.1:5984
export BD_HOST_ROOT=homeworks@127.0.0.1:/volume1
export BD_PROJECT=wfg
export BD_DB=$BD_PROJECT

export BD_TOOLSVER=0.1.0
export BD_TOOLS=`pwd`
export BD_ICONS=$BD_TOOLS/icons
export PYTHONPATH=$BD_ASS:$BD_TOOLS:$PYTHONPATH
export PATH=`pwd`/bin:$PATH

rez-env pyside pycouchdb liclipse sublime